# Generated by Django 2.2.2 on 2019-06-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_anticipating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckSentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
